### ISSUE TITLE
Crashed Cura 4.1

### ISSUE THREAD

**Issue by TAOGde** [q244200221/FlyingBear_TS_WIFI_4.0#1]
here are the two error log windows:

> Traceback (most recent call last):
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/FlyingBearPlugin/FlyingBearStage.py", line 62, in init_jz_plugin
>     self.plugin_main.init_stage(self.plugin_ui_item,self.upload_file_name)
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/FlyingBearPlugin/PluginMain.py", line 365, in init_stage
>     self.bind_ui()
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/FlyingBearPlugin/PluginMain.py", line 405, in bind_ui
>     self.update_history_ip()
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/FlyingBearPlugin/PluginMain.py", line 315, in update_history_ip
>     model.setItemData(model.createIndex(i,0), {1:"",0:"False"})
> RuntimeError: no access to protected functions or signals for objects not created from Python
> 

second:

> `Thread` 0x000070000e335000 (most recent call first):
>   File "/Applications/CAD Software/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000de32000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 297 in wait
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/OctoPrintPlugin/OctoPrintPlugin/zeroconf.py", line 1583 in wait
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/OctoPrintPlugin/OctoPrintPlugin/zeroconf.py", line 1167 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000d92f000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 297 in wait
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/OctoPrintPlugin/OctoPrintPlugin/zeroconf.py", line 1583 in wait
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/OctoPrintPlugin/OctoPrintPlugin/zeroconf.py", line 1031 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000d42c000 (most recent call first):
>   File "/Users/taog/Library/Application Support/cura/4.1/plugins/OctoPrintPlugin/OctoPrintPlugin/zeroconf.py", line 960 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000cf29000 (most recent call first):
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 150 in _storeStderrToLogThread
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000ca26000 (most recent call first):
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 138 in _storeOutputToLogThread
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000c4a0000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000bf9d000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000ba9a000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000b597000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000b094000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000ab91000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000a68e000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x000070000a18b000 (most recent call first):
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Current thread 0x0000000116c4e5c0 (most recent call first):
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 306 in _logInfoWidget
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 156 in _createDialog
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 77 in __init__
>   File "/Users/ultimaker/build/4.1/build/inst/bin/cura_app.py", line 102 in exceptHook
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 341 in exec_
>   File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 797 in run
>   File "/Users/ultimaker/build/4.1/build/inst/bin/cura_app.py", line 136 in <module>
>   File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 969 in _find_and_load
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21 in <module>
>   File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 969 in _find_and_load
>   File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12 in <module>
>   File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 969 in _find_and_load
> `

**Comment by haegar33** [comment]
Got the same problem. I simply disabled the code at line 315 for "update_history_ip".  I may not have a history but the plugin works fine now with Python 3.7 on MacOS 10.12.4

**Comment by TAOGde** [comment]
> Got the same problem. I simply disabled the code at line 315 for "update_history_ip". I may not have a history but the plugin works fine now with Python 3.7 on MacOS 10.12.4

i will test it with the actual version of Wifi and Cura.
